const urlParams = new URLSearchParams(window.location.search);
const productId = urlParams.get("id");
const product = menuItemsData.find(product => product.id == productId);
const productName = document.getElementById("product-name");
productName.innerHTML = product.title;
// const productRating = document.getElementById("rating");
// productRating.innerHTML = product.rating;
const productDescription = document.getElementById("product-description");
productDescription.innerHTML = product.description;
const productImage = document.getElementById("product-image");
productImage.style.backgroundImage = `url(${product.image})`;
const productPrice = document.getElementById("product-price");
productPrice.innerHTML = `Price : &#x20B9; ${product.price}`;